### PR TITLE
Use an explicit source name for vlc presence test

### PR DESCRIPTION
**Pull request by orion78fr**
Was clearly asking myself what this dummy9873945 source was

### CODE REVIEW

**Comment by univrsal** [comment]
Wait it shows up in obs?

**Comment by orion78fr** [comment]
Yup in the logs
```
22:23:31.789: Source ID 'vlc_source' not found
22:23:31.790: Failed to create source 'tuna_module_load_vlc_presence_test_source'!
```

**Comment by orion78fr** [comment]
Btw I think you broke something in linux build with your logging in the timeout

**Comment by univrsal** [comment]
Yeah I saw that, I'll get to it later.

**Pull request merged**
