### PR TITLE
Update widget.html

### PR DESCRIPTION
**Pull request by StupidShibaCat**
testing circular styled covers.

### CODE REVIEW

**Comment by univrsal** [comment]
I think the cover looks fine the way it is.

**Comment by syxize** [comment]
> 

Would still be cool and pretty simple as I see it at the first look. Cant you just define another css class and id for the round one: 

#cover-round{
        height: 100%;
        transition: background-image 0.8s ease-in-out;
        aspect-ratio: 1;
        background-size: contain;
        border-radius: 50%;
        box-shadow: 0 0 4px 4px rgba(0, 0, 0, .5) inset;
    }

    .image-box-round {

        border-radius: 50%;
        border-width: 1px;
        height: 100%;
        float: left;
    }

    .image-box-round img {
        position: relative;
        z-index: -1;
        border-radius: 50%;
    }

The square one than as it is as alternative option or vice versa depending on your coosing within the GUI. You would need to implement a simple switch and adjust GUI.

**Comment by syxize** [comment]
> I think the cover looks fine the way it is.

An attempt to make the cover circular. Either could be integrated into it's own folder for another cover type so user can select freely, or alternatively merge with current cover functions and allow circular crop type to be selected from integrated Tuna menu. Per example with Fetch Cover, additionally below saying "Change cover image to circle".

 #cover-round{
    height: 100%;
    transition: background-image 0.8s ease-in-out;
    aspect-ratio: 1;
    background-size: contain;
    border-radius: 50%;
    box-shadow: 0 0 4px 4px rgba(0, 0, 0, .5) inset;
 }

 .image-box-round {
    border-radius: 50%;
    border-width: 1px;
    height: 100%;
    float: left;
 }

 .image-box-round img {
    position: relative;
    z-index: -1;
    border-radius: 50%;
 }

**Comment by univrsal** [comment]
I'd like to keep the widget as simple as possible since it's just an example. If someone makes a new one with a different look (ideally not just some minor adjustments to the existing one) it can be submitted in a PR as separate html file.

**Pull request closed without merging**
